name: myworkflow
on:
  push:
    branches:
      - 'v[0-9]+.[0-9]+'

jobs:
  my_first_ci:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/codebuhui/fortunes:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/codebuhui/fortunes:${{ github.sha }}'
          format: 'table'
          output: 'Failure.txt'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      
      - name: Slack Notification
        if: ${{failure()}}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.TEST }} 
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: 'Failed trivy scan, see uploaded report'
          SLACK_TITLE: Scan Failed

      - uses: MeilCli/slack-upload-file@v3
        if: ${{failure()}}
        with:
          slack_token: ${{ secrets.TOKENTEST}}
          channel_id: ${{ secrets.ID }}
          file_path: './Failure.txt'
          initial_comment: 'codebuhui Scan Report'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{secrets.DOCKERHUB_NAME}}/fortunes:${{ github.sha }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1
      - name: Check install!
        run: cosign version

      - name : Generate key pair
        run: |
            cosign generate-key-pair

      - name: Sign image with a key
        run: |
              cosign sign --yes --key cosign.key docker.io/codebuhui/fortunes:${{ github.sha }}

      
      - name: pubkey file
        run: |
              git config --global user.email wangwyh78@gmail.com
              git config --global user.name codebuhui
              git add .
              git reset cosign.key
              git commit -m "add pubkey file"
              git push -u origin v1.2


      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_WEBHOOK: ${{ secrets.TEST }} 
            SLACK_COLOR: ${{ job.status }}
            SLACK_TITLE: image build and signed by codebuhui
            SLACK_MESSAGE: |
              *Name:* WANG YIHAN
              *Metriculation:* A0285882L
              *Email:* <a href="mailto:e1221694@u.nus.edu">e1221694@u.nus.edu</a>
              *Repository: *<a href="${{ secrets.REPOSITORY }}">Your Repository Name</a>
              *DockerHubURL: *<a href="${{ secrets.DOCKERHUB_URL }}">DockerHub URL</a>
      


     